export const apExams = [
	'2-D Art and Design',
	'3-D Art and Design',
	'Art History',
	'Biology',
	'Calculus AB',
	'Calculus BC',
	'Chemistry',
	'Chinese Language and Culture',
	'Comparative Government and Politics',
	'Computer Science A',
	'Computer Science Principles',
	'Drawing',
	'English Language and Composition',
	'English Literature and Composition',
	'Environmental Science',
	'European History',
	'French Language and Culture',
	'German Language and Culture',
	'Human Geography',
	'Italian Language and Culture',
	'Japanese Language and Culture',
	'Latin',
	'Macroeconomics',
	'Microeconomics',
	'Music Theory',
	'Physics 1',
	'Physics 2',
	'Physics C: Electricity and Magnetism',
	'Physics C: Mechanics',
	'Precalculus',
	'Psychology',
	'Research',
	'Seminar',
	'Spanish Language and Culture',
	'Spanish Literature and Culture',
	'Statistics',
	'US Government and Politics',
	'US History',
	'World History: Modern'
] as const;

export const ibExams = [
	'Arabic A: Language and Literature HL',
	'Arabic A: Language and Literature SL',
	'Arabic A: Literature HL',
	'Arabic A: Literature SL',
	'Arabic B HL',
	'Arabic B SL',
	'Arabic ab initio SL',
	'Biology HL',
	'Biology SL',
	'Business Management HL',
	'Business Management SL',
	'Chemistry HL',
	'Chemistry SL',
	'Chinese A: Language and Literature HL',
	'Chinese A: Language and Literature SL',
	'Chinese A: Literature HL',
	'Chinese A: Literature SL',
	'Chinese B HL',
	'Chinese B SL',
	'Chinese ab initio SL',
	'Classical Greek HL',
	'Classical Greek SL',
	'Computer Science HL',
	'Computer Science SL',
	'Dance HL',
	'Dance SL',
	'Design Technology HL',
	'Design Technology SL',
	'Dutch A: Language and Literature HL',
	'Dutch A: Language and Literature SL',
	'Dutch A: Literature HL',
	'Dutch A: Literature SL',
	'Dutch B HL',
	'Dutch B SL',
	'Dutch ab initio SL',
	'Economics HL',
	'Economics SL',
	'English A: Language and Literature HL',
	'English A: Language and Literature SL',
	'English A: Literature HL',
	'English A: Literature SL',
	'English B HL',
	'English B SL',
	'English ab initio SL',
	'Environmental Systems and Societies SL',
	'Extended Essay',
	'Film HL',
	'Film SL',
	'French A: Language and Literature HL',
	'French A: Language and Literature SL',
	'French A: Literature HL',
	'French A: Literature SL',
	'French B HL',
	'French B SL',
	'French ab initio SL',
	'Geography HL',
	'Geography SL',
	'German A: Language and Literature HL',
	'German A: Language and Literature SL',
	'German A: Literature HL',
	'German A: Literature SL',
	'German B HL',
	'German B SL',
	'German ab initio SL',
	'Global Politics HL',
	'Global Politics SL',
	'History HL',
	'History SL',
	'Indonesian A: Language and Literature HL',
	'Indonesian A: Language and Literature SL',
	'Indonesian A: Literature HL',
	'Indonesian A: Literature SL',
	'Indonesian B HL',
	'Indonesian B SL',
	'Indonesian ab initio SL',
	'Information Technology in a Global Society HL',
	'Information Technology in a Global Society SL',
	'Italian A: Language and Literature HL',
	'Italian A: Language and Literature SL',
	'Italian A: Literature HL',
	'Italian A: Literature SL',
	'Italian B HL',
	'Italian B SL',
	'Italian ab initio SL',
	'Japanese A: Language and Literature HL',
	'Japanese A: Language and Literature SL',
	'Japanese A: Literature HL',
	'Japanese A: Literature SL',
	'Japanese B HL',
	'Japanese B SL',
	'Japanese ab initio SL',
	'Korean A: Language and Literature HL',
	'Korean A: Language and Literature SL',
	'Korean A: Literature HL',
	'Korean A: Literature SL',
	'Korean B HL',
	'Korean B SL',
	'Korean ab initio SL',
	'Latin HL',
	'Latin SL',
	'Literature and Performance SL',
	'Mathematics: Analysis and Approaches HL',
	'Mathematics: Analysis and Approaches SL',
	'Mathematics: Applications and Interpretation HL',
	'Mathematics: Applications and Interpretation SL',
	'Music HL',
	'Music SL',
	'Norwegian A: Language and Literature HL',
	'Norwegian A: Language and Literature SL',
	'Norwegian A: Literature HL',
	'Norwegian A: Literature SL',
	'Norwegian B HL',
	'Norwegian B SL',
	'Norwegian ab initio SL',
	'Philosophy HL',
	'Philosophy SL',
	'Physics HL',
	'Physics SL',
	'Portuguese A: Language and Literature HL',
	'Portuguese A: Language and Literature SL',
	'Portuguese A: Literature HL',
	'Portuguese A: Literature SL',
	'Portuguese B HL',
	'Portuguese B SL',
	'Portuguese ab initio SL',
	'Psychology HL',
	'Psychology SL',
	'Russian A: Language and Literature HL',
	'Russian A: Language and Literature SL',
	'Russian A: Literature HL',
	'Russian A: Literature SL',
	'Russian B HL',
	'Russian B SL',
	'Russian ab initio SL',
	'Social and Cultural Anthropology HL',
	'Social and Cultural Anthropology SL',
	'Spanish A: Language and Literature HL',
	'Spanish A: Language and Literature SL',
	'Spanish A: Literature HL',
	'Spanish A: Literature SL',
	'Spanish B HL',
	'Spanish B SL',
	'Spanish ab initio SL',
	'Sports, Exercise, and Health Science HL',
	'Sports, Exercise, and Health Science SL',
	'Swedish A: Language and Literature HL',
	'Swedish A: Language and Literature SL',
	'Swedish A: Literature HL',
	'Swedish A: Literature SL',
	'Swedish B HL',
	'Swedish B SL',
	'Swedish ab initio SL',
	'Thai A: Language and Literature HL',
	'Thai A: Language and Literature SL',
	'Thai A: Literature HL',
	'Thai A: Literature SL',
	'Thai B HL',
	'Thai B SL',
	'Thai ab initio SL',
	'Theatre HL',
	'Theatre SL',
	'Theory of Knowledge',
	'Visual Arts HL',
	'Visual Arts SL',
	'World Religions SL'
] as const;

export const alevelExams = [
	'Accounting',
	'Arabic',
	'Art & Design',
	'Biblical Studies',
	'Biology',
	'Business',
	'Chemistry',
	'Chinese - Language & Literature',
	'Chinese',
	'Classical Studies',
	'Computer Science',
	'Design & Technology',
	'Design & Textiles',
	'Digital Media & Design',
	'Drama',
	'Economics',
	'English - Literature',
	'English Language',
	'Extended Project Qualification',
	'French',
	'French Language & Literature',
	'Geography',
	'German',
	'German Language & Literature',
	'Global Perspectives & Research',
	'Hindi',
	'Hinduism',
	'History',
	'Information Technology',
	'Islamic Studies',
	'Law',
	'Marine Science',
	'Mathematics',
	'Mathematics - Further',
	'Media Studies',
	'Music',
	'Physical Education',
	'Physics',
	'Portuguese',
	'Psychology',
	'Sociology',
	'Spanish - Language & Literature',
	'Spanish',
	'Tamil - Language',
	'Thinking Skills',
	'Travel & Tourism',
	'Urdu'
] as const;
