export const apExams = [
	'2-D Art and Design',
	'3-D Art and Design',
	'Art History',
	'Biology',
	'Calculus AB',
	'Calculus BC',
	'Chemistry',
	'Chinese Language and Culture',
	'Comparative Government and Politics',
	'Computer Science A',
	'Computer Science Principles',
	'Drawing',
	'English Language and Composition',
	'English Literature and Composition',
	'Environmental Science',
	'European History',
	'French Language and Culture',
	'German Language and Culture',
	'Human Geography',
	'Italian Language and Culture',
	'Japanese Language and Culture',
	'Latin',
	'Macroeconomics',
	'Microeconomics',
	'Music Theory',
	'Physics 1',
	'Physics 2',
	'Physics C: Electricity and Magnetism',
	'Physics C: Mechanics',
	'Precalculus',
	'Psychology',
	'Research',
	'Seminar',
	'Spanish Language and Culture',
	'Spanish Literature and Culture',
	'Statistics',
	'US Government and Politics',
	'US History',
	'World History: Modern'
] as const;

export const ibExams = [
	'Biology HL',
	'Biology SL',
	'Business Management HL',
	'Business Management SL',
	'Chemistry HL',
	'Chemistry SL',
	'Classical Languages HL',
	'Classical Languages SL',
	'Computer Science HL',
	'Computer Science SL',
	'Dance HL',
	'Dance SL',
	'Design Technology HL',
	'Design Technology SL',
	'Economics HL',
	'Economics SL',
	'Environmental Systems and Societies SL',
	'Film HL',
	'Film SL',
	'Geography HL',
	'Geography SL',
	'Global Politics HL',
	'Global Politics SL',
	'History HL',
	'History SL',
	'Information Technology in a Global Society HL',
	'Information Technology in a Global Society SL',
	'Language A: Language & Literature HL',
	'Language A: Language & Literature SL',
	'Language A: Literature HL',
	'Language A: Literature SL',
	'Language B HL',
	'Language B SL',
	'Language ab Initio SL',
	'Literature and Performance SL',
	'Mathematics: Analysis and Approaches HL',
	'Mathematics: Analysis and Approaches SL',
	'Mathematics: Applications and Interpretation HL',
	'Mathematics: Applications and Interpretation SL',
	'Music HL',
	'Music SL',
	'Philosophy HL',
	'Philosophy SL',
	'Physics HL',
	'Physics SL',
	'Psychology HL',
	'Psychology SL',
	'Social and Cultural Anthropology HL',
	'Social and Cultural Anthropology SL',
	'Sports, Exercise, and Health Science HL',
	'Sports, Exercise, and Health Science SL',
	'Theatre HL',
	'Theatre SL',
	'Visual Arts HL',
	'Visual Arts SL',
	'World Religions SL'
] as const;

export const alevelExams = [
	'Accounting',
	'Arabic',
	'Art & Design',
	'Biblical Studies',
	'Biology',
	'Business',
	'Chemistry',
	'Chinese - Language & Literature',
	'Chinese',
	'Classical Studies',
	'Computer Science',
	'Design & Technology',
	'Design & Textiles',
	'Digital Media & Design',
	'Drama',
	'Economics',
	'English - Literature',
	'English Language',
	'French',
	'French Language & Literature',
	'Geography',
	'German',
	'German Language & Literature',
	'Global Perspectives & Research',
	'Hindi',
	'Hinduism',
	'History',
	'Information Technology',
	'Islamic Studies',
	'Law',
	'Marine Science',
	'Mathematics',
	'Mathematics - Further',
	'Media Studies',
	'Music',
	'Physical Education',
	'Physics',
	'Portuguese',
	'Psychology',
	'Sociology',
	'Spanish - Language & Literature',
	'Spanish',
	'Tamil - Language',
	'Thinking Skills',
	'Travel & Tourism',
	'Urdu'
] as const;
