const countryFlags: { [key: string]: string } = {
	// Australia and New Zealand
	Australia: '🇦🇺',
	'New Zealand': '🇳🇿',

	// East Asian countries
	China: '🇨🇳',
	'Hong Kong': '🇭🇰',
	Japan: '🇯🇵',
	Macao: '🇲🇴',
	Mongolia: '🇲🇳',
	'North Korea': '🇰🇵',
	'South Korea': '🇰🇷',
	Taiwan: '🇹🇼',

	// European countries
	Albania: '🇦🇱',
	Andorra: '🇦🇩',
	Armenia: '🇦🇲',
	Austria: '🇦🇹',
	Azerbaijan: '🇦🇿',
	Belarus: '🇧🇾',
	Belgium: '🇧🇪',
	'Bosnia and Herzegovina': '🇧🇦',
	Bulgaria: '🇧🇬',
	Croatia: '🇭🇷',
	Cyprus: '🇨🇾',
	'Czech Republic': '🇨🇿',
	Denmark: '🇩🇰',
	Estonia: '🇪🇪',
	Finland: '🇫🇮',
	France: '🇫🇷',
	Georgia: '🇬🇪',
	Germany: '🇩🇪',
	Greece: '🇬🇷',
	Hungary: '🇭🇺',
	Iceland: '🇮🇸',
	Ireland: '🇮🇪',
	Italy: '🇮🇹',
	Kazakhstan: '🇰🇿',
	Kosovo: '🇽🇰',
	Latvia: '🇱🇻',
	Liechtenstein: '🇱🇮',
	Lithuania: '🇱🇹',
	Luxembourg: '🇱🇺',
	Malta: '🇲🇹',
	Moldova: '🇲🇩',
	Monaco: '🇲🇨',
	Montenegro: '🇲🇪',
	Netherlands: '🇳🇱',
	'North Macedonia': '🇲🇰',
	Norway: '🇳🇴',
	Poland: '🇵🇱',
	Portugal: '🇵🇹',
	Romania: '🇷🇴',
	Russia: '🇷🇺',
	'San Marino': '🇸🇲',
	Serbia: '🇷🇸',
	Slovakia: '🇸🇰',
	Slovenia: '🇸🇮',
	Spain: '🇪🇸',
	Sweden: '🇸🇪',
	Switzerland: '🇨🇭',
	Turkey: '🇹🇷',
	Ukraine: '🇺🇦',
	'United Kingdom': '🇬🇧',
	'Vatican City': '🇻🇦',

	// North American countries
	'Antigua and Barbuda': '🇦🇬',
	Bahamas: '🇧🇸',
	Barbados: '🇧🇧',
	Belize: '🇧🇿',
	Canada: '🇨🇦',
	'Costa Rica': '🇨🇷',
	Cuba: '🇨🇺',
	Dominica: '🇩🇲',
	'Dominican Republic': '🇩🇴',
	'El Salvador': '🇸🇻',
	Grenada: '🇬🇩',
	Guatemala: '🇬🇹',
	Haiti: '🇭🇹',
	Honduras: '🇭🇳',
	Jamaica: '🇯🇲',
	Mexico: '🇲🇽',
	Nicaragua: '🇳🇮',
	Panama: '🇵🇦',
	'Saint Kitts and Nevis': '🇰🇳',
	'Saint Lucia': '🇱🇨',
	'Saint Vincent and the Grenadines': '🇻🇨',
	'Trinidad and Tobago': '🇹🇹',
	'United States': '🇺🇸',

	// Southeast Asian countries
	Brunei: '🇧🇳',
	Cambodia: '🇰🇭',
	'East Timor': '🇹🇱',
	Indonesia: '🇮🇩',
	Laos: '🇱🇦',
	Malaysia: '🇲🇾',
	Myanmar: '🇲🇲',
	Philippines: '🇵🇭',
	Singapore: '🇸🇬',
	Thailand: '🇹🇭',
	Vietnam: '🇻🇳'
};

export default countryFlags;
