# Generated by Django 5.0.7 on 2024-08-07 19:21

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0013_application_application_unique_contract_round'),
        ('target', '0006_alter_programiteration_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACTScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('english', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('math', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reading', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('science', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('writing', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='act', to='core.student')),
            ],
            options={
                'verbose_name_plural': 'ACT scores',
            },
        ),
        migrations.CreateModel(
            name='ALevelGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('percentage', models.SmallIntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alevel', to='core.student')),
            ],
            options={
                'verbose_name_plural': 'A-level grades',
            },
        ),
        migrations.CreateModel(
            name='APScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('subject', models.CharField(max_length=100)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ap', to='core.student')),
            ],
            options={
                'verbose_name_plural': 'AP scores',
            },
        ),
        migrations.CreateModel(
            name='DuolingoScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('overall', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('literacy', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comprehension', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('conversation', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('production', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duolingo', to='core.student')),
            ],
            options={
                'verbose_name_plural': 'Duolingo scores',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_type', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('start_progression', models.CharField(blank=True, max_length=50)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_progression', models.CharField(blank=True, max_length=50)),
                ('curriculum', models.CharField(blank=True, max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='target.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='GMATScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('verbal', models.SmallIntegerField(blank=True, null=True)),
                ('quant', models.SmallIntegerField(blank=True, null=True)),
                ('reasoning', models.SmallIntegerField(blank=True, null=True)),
                ('writing', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gmat', to='core.student')),
            ],
            options={
                'verbose_name_plural': 'GMAT scores',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progression', models.CharField(max_length=50)),
                ('term', models.CharField(max_length=20)),
                ('value', models.DecimalField(decimal_places=3, max_digits=6)),
                ('scale', models.DecimalField(decimal_places=3, max_digits=6)),
                ('is_cumulative', models.BooleanField(default=False)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academics.enrollment')),
            ],
        ),
        migrations.CreateModel(
            name='GREScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('verbal', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quant', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('writing', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gre', to='core.student')),
            ],
            options={
                'verbose_name_plural': 'GRE scores',
            },
        ),
        migrations.CreateModel(
            name='IBGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ib', to='core.student')),
            ],
            options={
                'verbose_name_plural': 'IB grades',
            },
        ),
        migrations.CreateModel(
            name='IELTSScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('listening', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('reading', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('writing', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('speaking', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ielts', to='core.student')),
            ],
            options={
                'verbose_name_plural': 'IELTS scores',
            },
        ),
        migrations.CreateModel(
            name='LSATScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lsat', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='SATScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('ebrw', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('math', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('essay', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sat', to='core.student')),
            ],
            options={
                'verbose_name_plural': 'SAT scores',
            },
        ),
        migrations.CreateModel(
            name='TOEFLScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('reading', models.SmallIntegerField(blank=True, null=True)),
                ('listening', models.SmallIntegerField(blank=True, null=True)),
                ('speaking', models.SmallIntegerField(blank=True, null=True)),
                ('writing', models.SmallIntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toefl', to='core.student')),
            ],
            options={
                'verbose_name_plural': 'TOEFL scores',
            },
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(models.F('student'), models.F('school'), django.db.models.functions.text.Lower('program_type'), models.F('start_date'), name='enrollment_unique_student_school_type_startdate'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(models.F('enrollment'), django.db.models.functions.text.Lower('progression'), django.db.models.functions.text.Lower('term'), models.F('is_cumulative'), name='grades_unique_enrollment_progression_term_iscumulative'),
        ),
    ]
