# Generated by Django 5.0.7 on 2024-08-07 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lsatscore',
            options={'verbose_name_plural': 'LSAT scores'},
        ),
    ]
