# Generated by Django 5.0.7 on 2024-08-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_lsatscore_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='grade',
            name='grades_unique_enrollment_progression_term_iscumulative',
        ),
        migrations.AddField(
            model_name='grade',
            name='comments',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
