# Generated by Django 5.0.7 on 2024-08-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_remove_grade_grades_unique_enrollment_progression_term_iscumulative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='scale',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
