# Generated by Django 5.0.7 on 2024-08-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_grade_scale_alter_grade_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='is_weighted',
            field=models.BooleanField(default=False),
        ),
    ]
