# Generated by Django 5.0.7 on 2024-08-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_gmatscore_data_insights'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmatscore',
            name='is_legacy',
            field=models.BooleanField(default=False),
        ),
    ]
