# Generated by Django 5.0.7 on 2024-09-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_gmatscore_is_legacy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': [models.Case(models.When(program_type="Master's", then=0), models.When(program_type='UG Transfer', then=1), models.When(program_type='UG Freshman', then=2), models.When(program_type='Secondary School', then=3), default=99, output_field=models.IntegerField()), models.OrderBy(models.F('end_date'), descending=True, nulls_first=True), models.Case(models.When(end_progression='Year 5', then=0), models.When(end_progression='Year 4', then=1), models.When(end_progression='Year 3', then=2), models.When(end_progression='Year 2', then=3), models.When(end_progression='Year 1', then=4), models.When(end_progression='G12', then=5), models.When(end_progression='G11', then=6), models.When(end_progression='G10', then=7), models.When(end_progression='G9', then=8), models.When(end_progression='G8', then=9), models.When(end_progression='G7', then=10)), models.Case(models.When(start_progression='Year 5', then=0), models.When(start_progression='Year 4', then=1), models.When(start_progression='Year 3', then=2), models.When(start_progression='Year 2', then=3), models.When(start_progression='Year 1', then=4), models.When(start_progression='G12', then=5), models.When(start_progression='G11', then=6), models.When(start_progression='G10', then=7), models.When(start_progression='G9', then=8), models.When(start_progression='G8', then=9), models.When(start_progression='G7', then=10))]},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': [models.Case(models.When(progression='G7', then=0), models.When(progression='G8', then=1), models.When(progression='G9', then=2), models.When(progression='G10', then=3), models.When(progression='G11', then=4), models.When(progression='G12', then=5), models.When(progression='Year 1', then=6), models.When(progression='Year 2', then=7), models.When(progression='Year 3', then=8), models.When(progression='Year 4', then=9), models.When(progression='Year 5', then=10), default=99, output_field=models.IntegerField()), models.Case(models.When(term='Fall', then=0), models.When(term='Winter', then=1), models.When(term='Spring', then=2), models.When(term='Summer', then=3), models.When(term='Year', then=4), default=99, output_field=models.IntegerField()), 'is_cumulative']},
        ),
    ]
