import { fontFamily } from 'tailwindcss/defaultTheme';

/** @type {import('tailwindcss').Config} */
const config = {
	darkMode: ['class'],
	content: ['./src/**/*.{html,js,svelte,ts}'],
	safelist: [
		'dark',
		// dynamic classes generated by score cards
		'h-[0px]',
		'h-[1px]',
		'h-[2px]',
		'h-[3px]',
		'h-[4px]',
		'h-[5px]',
		'h-[6px]',
		'h-[7px]',
		'h-[8px]',
		'h-[9px]',
		'h-[10px]',
		'h-[11px]',
		'h-[12px]',
		'h-[13px]',
		'h-[14px]',
		'h-[15px]',
		'h-[16px]',
		'h-[17px]',
		'h-[18px]',
		'h-[19px]',
		'h-[20px]',
		'h-[21px]',
		'h-[22px]',
		'h-[23px]',
		'h-[24px]',
		'h-[25px]',
		'h-[26px]',
		'h-[27px]',
		'h-[28px]',
		'h-[29px]',
		'h-[30px]',
		'h-[31px]',
		'h-[32px]',
		'h-[33px]',
		'h-[34px]',
		'h-[35px]',
		'h-[36px]',
		'h-[37px]',
		'h-[38px]',
		'h-[39px]',
		'h-[40px]',
		'h-[41px]',
		'h-[42px]',
		'h-[43px]',
		'h-[44px]',
		'h-[45px]',
		'h-[46px]',
		'h-[47px]',
		'h-[48px]',
		'h-[49px]',
		'h-[50px]',
		'h-[51px]',
		'h-[52px]',
		'h-[53px]',
		'h-[54px]',
		'h-[55px]',
		'h-[56px]',
		'h-[57px]',
		'h-[58px]',
		'h-[59px]',
		'h-[60px]',
		'h-[61px]',
		'h-[62px]',
		'h-[63px]',
		'h-[64px]',
		'h-[65px]',
		'h-[66px]',
		'h-[67px]',
		'h-[68px]',
		'h-[69px]',
		'h-[70px]',
		'h-[71px]',
		'h-[72px]'
	],
	theme: {
		container: {
			center: true,
			padding: '2rem',
			screens: {
				'2xl': '1400px'
			}
		},
		extend: {
			colors: {
				border: 'hsl(var(--border) / <alpha-value>)',
				input: 'hsl(var(--input) / <alpha-value>)',
				ring: 'hsl(var(--ring) / <alpha-value>)',
				background: 'hsl(var(--background) / <alpha-value>)',
				foreground: 'hsl(var(--foreground) / <alpha-value>)',
				primary: {
					DEFAULT: 'hsl(var(--primary) / <alpha-value>)',
					foreground: 'hsl(var(--primary-foreground) / <alpha-value>)'
				},
				secondary: {
					DEFAULT: 'hsl(var(--secondary) / <alpha-value>)',
					foreground: 'hsl(var(--secondary-foreground) / <alpha-value>)'
				},
				destructive: {
					DEFAULT: 'hsl(var(--destructive) / <alpha-value>)',
					foreground: 'hsl(var(--destructive-foreground) / <alpha-value>)'
				},
				muted: {
					DEFAULT: 'hsl(var(--muted) / <alpha-value>)',
					foreground: 'hsl(var(--muted-foreground) / <alpha-value>)'
				},
				accent: {
					DEFAULT: 'hsl(var(--accent) / <alpha-value>)',
					foreground: 'hsl(var(--accent-foreground) / <alpha-value>)'
				},
				popover: {
					DEFAULT: 'hsl(var(--popover) / <alpha-value>)',
					foreground: 'hsl(var(--popover-foreground) / <alpha-value>)'
				},
				card: {
					DEFAULT: 'hsl(var(--card) / <alpha-value>)',
					foreground: 'hsl(var(--card-foreground) / <alpha-value>)'
				},
				// custom colors
				// mint: {
				// 	50: '#f3faf3',
				// 	100: '#e4f4e5',
				// 	200: '#c9e9cb',
				// 	300: '#8dce93',
				// 	400: '#6dbb75',
				// 	500: '#499e51',
				// 	600: '#38813f',
				// 	700: '#2f6634',
				// 	800: '#29522e',
				// 	900: '#234427',
				// 	950: '#0f2412'
				// },
				mint: {
					50: '#faffe4',
					100: '#f2ffc5',
					200: '#e6ff91',
					300: '#d0ff52',
					400: '#b1fc03',
					500: '#9be300',
					600: '#76b600',
					700: '#5a8a01',
					800: '#486c08',
					900: '#3d5b0c',
					950: '#1e3300'
				},
				// cultured: {
				// 	50: '#f6f7ef',
				// 	100: '#e8e9d7',
				// 	200: '#dadbbf',
				// 	300: '#cbcea7',
				// 	400: '#bcc090',
				// 	500: '#adb379',
				// 	600: '#8d9664',
				// 	700: '#6e7850',
				// 	800: '#4f5b3c',
				// 	900: '#313f28'
				// },
				cultured: {
					50: '#faffe4',
					100: '#f2ffc5',
					200: '#e6ff91',
					300: '#d0ff52',
					400: '#b1fc03',
					500: '#9be300',
					600: '#76b600',
					700: '#5a8a01',
					800: '#486c08',
					900: '#3d5b0c',
					950: '#1e3300'
				}
			},
			borderRadius: {
				lg: 'var(--radius)',
				md: 'calc(var(--radius) - 2px)',
				sm: 'calc(var(--radius) - 4px)'
			},
			fontFamily: {
				sans: [...fontFamily.sans]
			}
		}
	}
};

export default config;
