# Generated by Django 5.0.7 on 2024-09-10 17:10

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddConstraint(
            model_name='academyproduct',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='academyproduct_unique_name'),
        ),
    ]
