# Generated by Django 5.0.7 on 2024-09-11 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cf', '0001_initial'),
        ('core', '0019_alter_student_academy_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcademyProduct',
            new_name='AcademyProgram',
        ),
    ]
