# Generated by Django 5.0.7 on 2024-09-11 09:16

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cf', '0002_rename_academyproduct_academyprogram'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='academyprogram',
            name='academyproduct_unique_name',
        ),
        migrations.AddConstraint(
            model_name='academyprogram',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='academyprogram_unique_name'),
        ),
    ]
