# Generated by Django 5.0.7 on 2024-09-11 09:47

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cf', '0003_remove_academyprogram_academyproduct_unique_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='academyprogram',
            name='academyprogram_unique_name',
        ),
        migrations.AddField(
            model_name='academyprogram',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='academyprogram',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), django.db.models.functions.text.Lower('category'), name='academyprogram_unique_name_category'),
        ),
    ]
