# Generated by Django 5.0.7 on 2024-07-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='base_country',
            field=models.CharField(default='China', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='comments',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
