# Generated by Django 5.0.7 on 2024-07-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student_base_country_alter_student_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='firstname_rm',
        ),
        migrations.RemoveField(
            model_name='student',
            name='lastname_rm',
        ),
        migrations.AddField(
            model_name='student',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
