# Generated by Django 5.0.7 on 2024-07-21 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_contract_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='base_state',
            new_name='base_subnational',
        ),
    ]
