# Generated by Django 5.0.7 on 2024-07-21 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_base_state_student_base_subnational'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='firstname',
            new_name='given_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='lastname',
            new_name='surname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='lastname_first',
            new_name='surname_first',
        ),
    ]
