# Generated by Django 5.0.7 on 2024-07-26 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_firstname_student_given_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='student_initial_progression',
            new_name='student_progression_when_signed',
        ),
    ]
