# Generated by Django 5.0.7 on 2024-08-03 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_service_service_service_unique_contract_cfer_role'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='application',
            name='application_unique_student_round',
        ),
        migrations.RemoveField(
            model_name='application',
            name='student',
        ),
        migrations.AddField(
            model_name='application',
            name='contract',
            field=models.ForeignKey(default=92, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.contract'),
            preserve_default=False,
        ),
    ]
