# Generated by Django 5.0.7 on 2024-08-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_application_application_unique_student_round_and_more'),
        ('target', '0006_alter_programiteration_program'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(models.F('contract'), models.F('round'), name='application_unique_contract_round'),
        ),
    ]
