# Generated by Django 5.0.7 on 2024-08-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_application_comments_application_major_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='track',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
