# Generated by Django 5.0.7 on 2024-09-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_application_application_unique_contract_round_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': [models.Case(models.When(status='In effect', then=models.Value(0)), default=models.Value(1), output_field=models.IntegerField()), '-target_year', models.Case(models.When(date__isnull=True, then=models.Value(1)), default=models.Value(0), output_field=models.IntegerField()), '-date']},
        ),
    ]
