# Generated by Django 5.0.7 on 2024-09-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cf', '0001_initial'),
        ('core', '0017_alter_contract_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academy_products',
            field=models.ManyToManyField(related_name='students', to='cf.academyproduct'),
        ),
    ]
