# Generated by Django 5.0.7 on 2024-09-11 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_student_academy_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='academy_products',
            new_name='cf_academy_programs',
        ),
    ]
