# Generated by Django 5.0.7 on 2025-03-23 03:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_academy_products_student_cf_academy_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
