# Generated by Django 5.0.7 on 2025-03-23 04:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_application_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
