# Generated by Django 5.0.7 on 2025-03-24 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_application_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='track',
        ),
    ]
