# Generated by Django 5.0.7 on 2025-04-29 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_application_track'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cfuser',
            old_name='private_banner',
            new_name='avatar',
        ),
    ]
